server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/northern_lights?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  servlet:
    multipart:
      enabled: true
      max-file-size: 12MB   # Define o tamanho máximo de cada arquivo
      max-request-size: 12MB # Define o tamanho máximo da requisição

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: false
        connection:
          characterEncoding: utf8
          useUnicode: true
    database-platform: ${DATABASE_PLATFORM:}

  sql:
    init:
      mode: always

  application:
    name: NORTHERN LIGHTS

  jackson:
    time-zone: America/Sao_Paulo

file:
  upload-dir: ${UPLOAD_DIR:uploads}

jwt:
  secret: ${JWT_SECRET:MinhaChaveSuperSecreta1234567890123456}
  expiration: ${JWT_EXPIRATION:86400000}
